### PR TITLE
fixing typos and ineffassign issues

### PR DESCRIPTION
**Pull request by tariq1890**
Thanks for this great library @daniel-nichter . Are you still around  :) ?

### CODE REVIEW

**Comment by daniel-nichter** [comment]
Oops, I fixed the ineffassign issue, too, before I saw that you already fixed it.

**Comment by tariq1890** [comment]
No worries. This PR can still be merged though :)

**Comment by daniel-nichter** [comment]
Thanks for the fix!

Was trying to get Travis CI GitHub app integration to work as a build/test check on PRs, but something isn't working. Will tinker with that later.

**Comment by daniel-nichter** [comment]
Oh, I did work, just not for the PR. Odd. Oh well, working now. :-)

**Comment by tariq1890** [comment]
Thanks for merging @daniel-nichter. Can we get a release cut from all the recent commits to this project?

**Comment by daniel-nichter** [comment]
Yep, already done: v1.0.2.

**Pull request merged**
